version: '3.1'

services:
  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trz
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  app:
    image: martinpetersen/the-resident-zombie:latest
    container_name: application
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_URL: ${DB_URL}
    ports:
      - "8081:8080"

volumes:
  database:
