spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:trz-database"
    username: "root"
    password: "root"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true
      path: "/h2-console"
